#pragma once

#include <cstdint>

namespace compiler
{
  namespace syntax
  {
    enum syntax_kind : uint32_t
    {
      SYNTAX_KIND_BAD_TOKEN,
      SYNTAX_KIND_END_OF_FILE_TOKEN,
      SYNTAX_KIND_IDENTIFIER_TOKEN,
      SYNTAX_KIND_INTEGER_LITERAL_TOKEN,
      SYNTAX_KIND_INT_KEYWORD,
      SYNTAX_KIND_RETURN_KEYWORD,
      SYNTAX_KIND_OPEN_PAREN_TOKEN,
      SYNTAX_KIND_CLOSE_PAREN_TOKEN,
      SYNTAX_KIND_OPEN_BRACE_TOKEN,
      SYNTAX_KIND_CLOSE_BRACE_TOKEN,
      SYNTAX_KIND_COMMA_TOKEN,
      SYNTAX_KIND_SEMICOLON_TOKEN,
      SYNTAX_KIND_TRANSLATION_UNIT,
      SYNTAX_KIND_FUNCTION_DEFINITION,
      SYNTAX_KIND_FUNCTION_DECLARATOR,
      SYNTAX_KIND_PARAMETER_LIST,
      SYNTAX_KIND_PARAMETER_DECLARATION,
      SYNTAX_KIND_COMPOUND_STATEMENT,
      SYNTAX_KIND_DECLARATION_STATEMENT,
      SYNTAX_KIND_RETURN_STATEMENT,
      SYNTAX_KIND_IDENTIFIER,
      SYNTAX_KIND_TYPE_SPECIFIER,
      SYNTAX_KIND_IDENTIFIER_EXPRESSION,
      SYNTAX_KIND_LITERAL_EXPRESSION,
      SYNTAX_KIND_MISSING,
      SYNTAX_KIND_ERROR,
    };

    [[nodiscard]] bool is_token_kind(syntax_kind kind);
  }
}
